### ISSUE TITLE
Stuck on has_metadata

### ISSUE THREAD

**Issue by mylich119** [danfolkes/Magnet2Torrent#15]
I strace the process and find it keep print info like below 
futex(0x1c6e41c, FUTEX_WAIT_PRIVATE, 97, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1c6e3f0, FUTEX_WAKE_PRIVATE, 1) = 0
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)

Do I need more settings or specific environment ? My test server is behind NAT

**Comment by danfolkes** [comment]
Do you have the line it is stuck on? Does it have an exception?
