### ISSUE TITLE
add_magnet_uri is deprecated

### ISSUE THREAD

**Issue by hpfn** [danfolkes/Magnet2Torrent#18]
Hi,

add_magnet_uri is deprecated.

I did a fork and made the changes.
https://github.com/hpfn/Magnet2Torrent/commit/09611b858c7a08be022899b8f6ef8de7e1328329

I tried to do a 'pull request', suppose to be simple. But
I do not know how.

regards

**Comment by abreksa4** [comment]
@hpfn Check out this link: https://gist.github.com/Chaser324/ce0505fbed06b947d962
and this one: https://help.github.com/articles/using-pull-requests/

I've opened a PR for you after forking your fork here: https://github.com/danfolkes/Magnet2Torrent/pull/21

**Comment by hpfn** [comment]
Hi Andrew Breksa,

> @hpfn Check out this link: https://gist.github.com/Chaser324/ce0505fbed06b947d962
> and this one: https://help.github.com/articles/using-pull-requests/
> 
> I've opened a PR for you after forking your fork here: https://github.com/danfolkes/Magnet2Torrent/pull/21

I will see the links.

Thanks!



regards,
-- 
Herbert Parentes Fortes Neto (hpfn)
