### ISSUE TITLE
Python3 support broken

### ISSUE THREAD

**Issue by LordAro** [danfolkes/Magnet2Torrent#20]
As noted by @parnmatt , https://github.com/danfolkes/Magnet2Torrent/commit/71da07139c7fbaf8747f11a8abcb13b26ab181af#diff-ee6d3490a40d516d8ec6de809896f74cR140 breaks the program with python3

You should either explicitly define python2 in the #! at the top of the file (please no), or fix the print - seems print() is used elsewhere already

**Comment by AdeebNqo** [comment]
Hi,

In issue #19, @parnmatt mentioned the issue (as you've noted). We did offer a way to fix it. I do not have write permissions on his branch so we cannot update his pull request hence we are waiting for him to implement our suggestion.

**Comment by parnmatt** [comment]
Ah; I believed that my pull request would be rejected and @danfolkes would remove the print statement.
I will update the request.
