### ISSUE TITLE
Latest libtorrent-rasterbar

### ISSUE THREAD

**Issue by Polichronucci** [danfolkes/Magnet2Torrent#24]
I am running magnet2torrent with the following dependencies
- python 3.5.2
- libtorrent-rasterbar 1:1.1.1

I get the following error.

```
Traceback (most recent call last):
  File "/usr/bin/magnet2torrent", line 34, in <module>
    import libtorrent as lt
ImportError: /usr/lib/libboost_python.so.1.61.0: undefined symbol: PyClass_Type
```

This error occurs by updating to the latest version of libtorrent-rasterbar, which in turn needs boost-libs version 1.61.0.

By using the following dependency versions magnet2torrent runs successfully.
- libtorrent-rasterbar-1:1.1
- boost-libs-1.60.0

**Comment by LordAro** [comment]
This is a bug in libtorrent-rasterbar, rather than magnet2torrent - (assuming arch) see https://bugs.archlinux.org/task/50745

**Comment by Polichronucci** [comment]
Yep, you're right. Closing...
