### ISSUE TITLE
libtorrent what's wrong?

### ISSUE THREAD

**Issue by lowy** [danfolkes/Magnet2Torrent#25]
Traceback (most recent call last):
  File "/usr/local/bin/Magnet_To_Torrent2.py", line 29, in <module>
    import libtorrent as lt
ImportError: /usr/lib64/python2.7/site-packages/libtorrent.so: undefined symbol: _ZTIN5boost6python15instance_holderE

system is fedora 25 x86_64

**Comment by requeijaum** [comment]
Seems that libtorrent-rasterbar is missing.
